export const MOCKED_DATA = [
    {
        "asin": "B0C4H2CHDV",
        "bought_in_last_month": 0,
        "category_name": "Accessories",
        "gender": "Men",
        "img_url": "https://m.media-amazon.com/images/I/516WGe4YvVL._AC_UL320_.jpg",
        "is_best_seller": true,
        "list_price": 0.0,
        "price": 15.99,
        "product_url": "https://www.amazon.com/dp/B0C4H2CHDV",
        "reviews": 2000,
        "stars": 0.0,
        "sub_category_id": 112,
        "sub_category_name": "Men's Accessories",
        "title": "Boston Cap Unisex Baseball Cap Sun Hat Adjustable Trucker Cap"
    },
    {
        "asin": "B09KLR74L5",
        "bought_in_last_month": 0,
        "category_name": "Accessories",
        "gender": "Men",
        "img_url": "https://m.media-amazon.com/images/I/71Q-sRhvUWL._AC_UL320_.jpg",
        "is_best_seller": true,
        "list_price": 0.0,
        "price": 49.99,
        "product_url": "https://www.amazon.com/dp/B09KLR74L5",
        "reviews": 2000,
        "stars": 4.7,
        "sub_category_id": 112,
        "sub_category_name": "Men's Accessories",
        "title": "Patch Harris Tweed Flat Cap Scally Cap for Men Scottish Hat Driving Cap Ivy Cap Irish Flat Hat Newsboy Cap"
    },
    {
        "asin": "B006K6HC0E",
        "bought_in_last_month": 0,
        "category_name": "Accessories",
        "gender": "Men",
        "img_url": "https://m.media-amazon.com/images/I/610RcZ1Q5kL._AC_UL320_.jpg",
        "is_best_seller": true,
        "list_price": 0.0,
        "price": 9.99,
        "product_url": "https://www.amazon.com/dp/B006K6HC0E",
        "reviews": 2000,
        "stars": 4.2,
        "sub_category_id": 112,
        "sub_category_name": "Men's Accessories",
        "title": "Cap"
    },
    {
        "asin": "B07S5CVN2T",
        "bought_in_last_month": 0,
        "category_name": "Accessories",
        "gender": "Men",
        "img_url": "https://m.media-amazon.com/images/I/51GdVn92AQL._AC_UL320_.jpg",
        "is_best_seller": true,
        "list_price": 0.0,
        "price": 16.97,
        "product_url": "https://www.amazon.com/dp/B07S5CVN2T",
        "reviews": 2000,
        "stars": 4.7,
        "sub_category_id": 112,
        "sub_category_name": "Men's Accessories",
        "title": "Cap"
    },
    {
        "asin": "B0BY1RLM2S",
        "bought_in_last_month": 50,
        "category_name": "Accessories",
        "gender": "Men",
        "img_url": "https://m.media-amazon.com/images/I/711lqCUNd2L._AC_UL320_.jpg",
        "is_best_seller": true,
        "list_price": 0.0,
        "price": 16.98,
        "product_url": "https://www.amazon.com/dp/B0BY1RLM2S",
        "reviews": 2000,
        "stars": 4.0,
        "sub_category_id": 112,
        "sub_category_name": "Men's Accessories",
        "title": "Small Head Baseball Cap,Petite Size Ball Cap,Relaxed Little Sports Cap,Adjustable Tiny Fitted Golf Cap"
    },
    {
        "asin": "B09DKCJL15",
        "bought_in_last_month": 0,
        "category_name": "Accessories",
        "gender": "Men",
        "img_url": "https://m.media-amazon.com/images/I/71RoWb0X87L._AC_UL320_.jpg",
        "is_best_seller": true,
        "list_price": 0.0,
        "price": 17.5,
        "product_url": "https://www.amazon.com/dp/B09DKCJL15",
        "reviews": 108,
        "stars": 4.5,
        "sub_category_id": 112,
        "sub_category_name": "Men's Accessories",
        "title": "Stylish Short Brim Soft Cap Baseball Cap Trucker/Baseball Style Hat Cap"
    },
    {
        "asin": "B07ZNZNCTQ",
        "bought_in_last_month": 0,
        "category_name": "Accessories",
        "gender": "Men",
        "img_url": "https://m.media-amazon.com/images/I/71zwSC0R7NL._AC_UL320_.jpg",
        "is_best_seller": true,
        "list_price": 0.0,
        "price": 24.8,
        "product_url": "https://www.amazon.com/dp/B07ZNZNCTQ",
        "reviews": 2000,
        "stars": 4.6,
        "sub_category_id": 112,
        "sub_category_name": "Men's Accessories",
        "title": "Bball 3s Cap Ct Unisex Adult Cap"
    },
    {
        "asin": "B008J4FZUO",
        "bought_in_last_month": 0,
        "category_name": "Accessories",
        "gender": "Men",
        "img_url": "https://m.media-amazon.com/images/I/71pHYS6N+8L._AC_UL320_.jpg",
        "is_best_seller": true,
        "list_price": 0.0,
        "price": 33.95,
        "product_url": "https://www.amazon.com/dp/B008J4FZUO",
        "reviews": 2000,
        "stars": 4.5,
        "sub_category_id": 112,
        "sub_category_name": "Men's Accessories",
        "title": "Radar Pocket Cap \u2013 Sun Protection Cadet Cap"
    },
    {
        "asin": "B0851X9CMX",
        "bought_in_last_month": 0,
        "category_name": "Accessories",
        "gender": "Men",
        "img_url": "https://m.media-amazon.com/images/I/613ugvNRKpL._AC_UL320_.jpg",
        "is_best_seller": true,
        "list_price": 0.0,
        "price": 51.12,
        "product_url": "https://www.amazon.com/dp/B0851X9CMX",
        "reviews": 2000,
        "stars": 4.3,
        "sub_category_id": 112,
        "sub_category_name": "Men's Accessories",
        "title": "Unisex P-6 Label Trad Cap Cap"
    },
    {
        "asin": "B0BLS1381G",
        "bought_in_last_month": 100,
        "category_name": "Accessories",
        "gender": "Men",
        "img_url": "https://m.media-amazon.com/images/I/917BSvecFAL._AC_UL320_.jpg",
        "is_best_seller": true,
        "list_price": 0.0,
        "price": 19.99,
        "product_url": "https://www.amazon.com/dp/B0BLS1381G",
        "reviews": 2000,
        "stars": 4.5,
        "sub_category_id": 112,
        "sub_category_name": "Men's Accessories",
        "title": "Cap Hat Classic Vintage Embroidered Hat Cap for Men Women Teenager Cap Adjustable"
    },
    {
        "asin": "B09Y48WBQG",
        "bought_in_last_month": 50,
        "category_name": "Accessories",
        "gender": "Men",
        "img_url": "https://m.media-amazon.com/images/I/71b6pZ135KL._AC_UL320_.jpg",
        "is_best_seller": true,
        "list_price": 0.0,
        "price": 19.99,
        "product_url": "https://www.amazon.com/dp/B09Y48WBQG",
        "reviews": 2000,
        "stars": 4.6,
        "sub_category_id": 112,
        "sub_category_name": "Men's Accessories",
        "title": "Cap Hat Classic Vintage Embroidered Hat Cap for Men Women Gift Cap Adjustable"
    },
    {
        "asin": "B0C8N5M7NB",
        "bought_in_last_month": 50,
        "category_name": "Accessories",
        "gender": "Men",
        "img_url": "https://m.media-amazon.com/images/I/61F+KYJWCOL._AC_UL320_.jpg",
        "is_best_seller": true,
        "list_price": 0.0,
        "price": 19.99,
        "product_url": "https://www.amazon.com/dp/B0C8N5M7NB",
        "reviews": 2000,
        "stars": 4.4,
        "sub_category_id": 112,
        "sub_category_name": "Men's Accessories",
        "title": "Cap Hat Classic Vintage Embroidered Hat Cap for Men Women Gift Cap Adjustable"
    },
    {
        "asin": "B0BKVX2DRM",
        "bought_in_last_month": 0,
        "category_name": "Accessories",
        "gender": "Men",
        "img_url": "No Image Found",
        "is_best_seller": true,
        "list_price": 0.0,
        "price": 0.0,
        "product_url": "https://www.amazon.com/dp/B0BKVX2DRM",
        "reviews": 2000,
        "stars": 0.0,
        "sub_category_id": 112,
        "sub_category_name": "Men's Accessories",
        "title": "Cap Hat Classic Vintage Embroidered Hat Cap for Men Women Gift Cap Adjustable"
    },
    {
        "asin": "B09Z2VDCLL",
        "bought_in_last_month": 50,
        "category_name": "Accessories",
        "gender": "Men",
        "img_url": "https://m.media-amazon.com/images/I/71SOkEj74lL._AC_UL320_.jpg",
        "is_best_seller": true,
        "list_price": 0.0,
        "price": 14.95,
        "product_url": "https://www.amazon.com/dp/B09Z2VDCLL",
        "reviews": 2000,
        "stars": 4.0,
        "sub_category_id": 112,
        "sub_category_name": "Men's Accessories",
        "title": "Military Hat, Army Hat, Conductor Hat, Military Cap, Army Cap, Cadet Hat, Cadet Cap, Patrol Cap,Painters Hat for Men"
    },
    {
        "asin": "B0B38ZVQHW",
        "bought_in_last_month": 0,
        "category_name": "Accessories",
        "gender": "Men",
        "img_url": "https://m.media-amazon.com/images/I/61Kusl75DoL._AC_UL320_.jpg",
        "is_best_seller": true,
        "list_price": 0.0,
        "price": 12.99,
        "product_url": "https://www.amazon.com/dp/B0B38ZVQHW",
        "reviews": 2000,
        "stars": 4.3,
        "sub_category_id": 112,
        "sub_category_name": "Men's Accessories",
        "title": "Men's Cotton Flat Cap Ivy Gatsby Newsboy Hat Summer Driving Scally Cap Thin Cap"
    },
    {
        "asin": "B08WTV6L14",
        "bought_in_last_month": 0,
        "category_name": "Accessories",
        "gender": "Men",
        "img_url": "https://m.media-amazon.com/images/I/81XU1icfYsL._AC_UL320_.jpg",
        "is_best_seller": true,
        "list_price": 0.0,
        "price": 17.99,
        "product_url": "https://www.amazon.com/dp/B08WTV6L14",
        "reviews": 2000,
        "stars": 4.1,
        "sub_category_id": 112,
        "sub_category_name": "Men's Accessories",
        "title": "Army Cap Everyday Military Style Baseball Cap Women Cotton Washed Tactical Operator Mens Cap"
    },
    {
        "asin": "B0727XX3HH",
        "bought_in_last_month": 100,
        "category_name": "Accessories",
        "gender": "Men",
        "img_url": "https://m.media-amazon.com/images/I/71Yg-VrOAHL._AC_UL320_.jpg",
        "is_best_seller": true,
        "list_price": 0.0,
        "price": 14.99,
        "product_url": "https://www.amazon.com/dp/B0727XX3HH",
        "reviews": 2000,
        "stars": 4.6,
        "sub_category_id": 112,
        "sub_category_name": "Men's Accessories",
        "title": "Men Wool Blend Newsboy Cap 8 Panel Hat Tweed Cap Herringbone Cabbie Flat Cap"
    },
    {
        "asin": "B00M47FC0K",
        "bought_in_last_month": 200,
        "category_name": "Accessories",
        "gender": "Men",
        "img_url": "https://m.media-amazon.com/images/I/715pN1kvOyL._AC_UL320_.jpg",
        "is_best_seller": true,
        "list_price": 0.0,
        "price": 27.95,
        "product_url": "https://www.amazon.com/dp/B00M47FC0K",
        "reviews": 2000,
        "stars": 4.7,
        "sub_category_id": 112,
        "sub_category_name": "Men's Accessories",
        "title": "Swift Cap \u2013 Sun Protection Cap for Women & Men"
    },
    {
        "asin": "B00318BKGQ",
        "bought_in_last_month": 100,
        "category_name": "Accessories",
        "gender": "Men",
        "img_url": "https://m.media-amazon.com/images/I/81WmjhYGdnL._AC_UL320_.jpg",
        "is_best_seller": true,
        "list_price": 0.0,
        "price": 24.95,
        "product_url": "https://www.amazon.com/dp/B00318BKGQ",
        "reviews": 2000,
        "stars": 4.4,
        "sub_category_id": 112,
        "sub_category_name": "Men's Accessories",
        "title": "Skull Cap - The Ultimate High Performance Skull Cap"
    },
    {
        "asin": "B08VDCCZL1",
        "bought_in_last_month": 0,
        "category_name": "Accessories",
        "gender": "Men",
        "img_url": "https://m.media-amazon.com/images/I/51kFqzlgPnL._AC_UL320_.jpg",
        "is_best_seller": true,
        "list_price": 50.0,
        "price": 47.5,
        "product_url": "https://www.amazon.com/dp/B08VDCCZL1",
        "reviews": 2000,
        "stars": 4.8,
        "sub_category_id": 112,
        "sub_category_name": "Men's Accessories",
        "title": "Seattle Rain Cap \u2013 Waterproof & Sun Protected Baseball Cap"
    },
    {
        "asin": "B08DFSPPRT",
        "bought_in_last_month": 100,
        "category_name": "Accessories",
        "gender": "Men",
        "img_url": "https://m.media-amazon.com/images/I/51SRoPFNdeL._AC_UL320_.jpg",
        "is_best_seller": true,
        "list_price": 0.0,
        "price": 14.99,
        "product_url": "https://www.amazon.com/dp/B08DFSPPRT",
        "reviews": 2000,
        "stars": 4.3,
        "sub_category_id": 112,
        "sub_category_name": "Men's Accessories",
        "title": "Men Ivy Cap Cotton Twill Newsboy Flat Cap"
    },
    {
        "asin": "B01GGO27DQ",
        "bought_in_last_month": 0,
        "category_name": "Accessories",
        "gender": "Men",
        "img_url": "https://m.media-amazon.com/images/I/61zTZj3D-PL._AC_UL320_.jpg",
        "is_best_seller": true,
        "list_price": 0.0,
        "price": 285.0,
        "product_url": "https://www.amazon.com/dp/B01GGO27DQ",
        "reviews": 41,
        "stars": 4.7,
        "sub_category_id": 114,
        "sub_category_name": "Men's Shoes",
        "title": "Market Cap"
    },
    {
        "asin": "B09FXL2YDY",
        "bought_in_last_month": 0,
        "category_name": "Accessories",
        "gender": "Men",
        "img_url": "https://m.media-amazon.com/images/I/71X+jT-91BL._AC_UL320_.jpg",
        "is_best_seller": true,
        "list_price": 350.0,
        "price": 310.0,
        "product_url": "https://www.amazon.com/dp/B09FXL2YDY",
        "reviews": 2000,
        "stars": 4.7,
        "sub_category_id": 112,
        "sub_category_name": "Men's Accessories",
        "title": "Collection Cap"
    },
    {
        "asin": "B095PXZQGH",
        "bought_in_last_month": 0,
        "category_name": "Accessories",
        "gender": "Men",
        "img_url": "https://m.media-amazon.com/images/I/81GIeberPkL._AC_UL320_.jpg",
        "is_best_seller": true,
        "list_price": 30.0,
        "price": 28.13,
        "product_url": "https://www.amazon.com/dp/B095PXZQGH",
        "reviews": 2000,
        "stars": 4.6,
        "sub_category_id": 112,
        "sub_category_name": "Men's Accessories",
        "title": "Tincan Cap"
    },
    {
        "asin": "B01J5J0F42",
        "bought_in_last_month": 0,
        "category_name": "Accessories",
        "gender": "Men",
        "img_url": "https://m.media-amazon.com/images/I/817iIfLAQpL._AC_UL320_.jpg",
        "is_best_seller": true,
        "list_price": 30.0,
        "price": 20.42,
        "product_url": "https://www.amazon.com/dp/B01J5J0F42",
        "reviews": 2000,
        "stars": 4.4,
        "sub_category_id": 112,
        "sub_category_name": "Men's Accessories",
        "title": "Aerial Cap"
    },
    {
        "asin": "B00QJ234N8",
        "bought_in_last_month": 0,
        "category_name": "Accessories",
        "gender": "Men",
        "img_url": "https://m.media-amazon.com/images/I/71zSHRzrK2L._AC_UL320_.jpg",
        "is_best_seller": true,
        "list_price": 0.0,
        "price": 28.99,
        "product_url": "https://www.amazon.com/dp/B00QJ234N8",
        "reviews": 2000,
        "stars": 4.4,
        "sub_category_id": 112,
        "sub_category_name": "Men's Accessories",
        "title": "USAF Cap"
    },
    {
        "asin": "B006RT52LK",
        "bought_in_last_month": 0,
        "category_name": "Accessories",
        "gender": "Men",
        "img_url": "https://m.media-amazon.com/images/I/611qd3+SQpL._AC_UL320_.jpg",
        "is_best_seller": true,
        "list_price": 0.0,
        "price": 19.95,
        "product_url": "https://www.amazon.com/dp/B006RT52LK",
        "reviews": 2000,
        "stars": 4.2,
        "sub_category_id": 112,
        "sub_category_name": "Men's Accessories",
        "title": "Marine Cap"
    },
    {
        "asin": "B0137VLF70",
        "bought_in_last_month": 0,
        "category_name": "Accessories",
        "gender": "Men",
        "img_url": "https://m.media-amazon.com/images/I/71zvWKOMaPL._AC_UL320_.jpg",
        "is_best_seller": true,
        "list_price": 16.44,
        "price": 15.17,
        "product_url": "https://www.amazon.com/dp/B0137VLF70",
        "reviews": 2000,
        "stars": 4.4,
        "sub_category_id": 112,
        "sub_category_name": "Men's Accessories",
        "title": "Delta Cap"
    },
    {
        "asin": "B003VSARVA",
        "bought_in_last_month": 0,
        "category_name": "Accessories",
        "gender": "Men",
        "img_url": "https://m.media-amazon.com/images/I/31XwvOz-bmL._AC_UL320_.jpg",
        "is_best_seller": true,
        "list_price": 0.0,
        "price": 28.99,
        "product_url": "https://www.amazon.com/dp/B003VSARVA",
        "reviews": 2000,
        "stars": 4.6,
        "sub_category_id": 112,
        "sub_category_name": "Men's Accessories",
        "title": "Piper Cap"
    },
    {
        "asin": "B0176IRIE4",
        "bought_in_last_month": 0,
        "category_name": "Accessories",
        "gender": "Men",
        "img_url": "https://m.media-amazon.com/images/I/61uGkGAPKFL._AC_UL320_.jpg",
        "is_best_seller": true,
        "list_price": 0.0,
        "price": 39.95,
        "product_url": "https://www.amazon.com/dp/B0176IRIE4",
        "reviews": 2000,
        "stars": 4.6,
        "sub_category_id": 112,
        "sub_category_name": "Men's Accessories",
        "title": "Helags Cap"
    }
]

export const MOCKED_ORDERS = [
    {
        "OrderID": "12345",
        "UserID": "user123",
        "OrderDate": "2024-01-01T12:00:00",
        "Products": [
        {
            "ProductID": "B0C4H2CHDV",
            "ProductName": "Boston Cap Unisex Baseball Cap Sun Hat Adjustable Trucker Cap",
            "ImageUrl": "https://m.media-amazon.com/images/I/516WGe4YvVL._AC_UL320_.jpg",
            "Quantity": 2,
            "Price": 29.99,
            "Color": "Red",
            "Size": "Medium",
            "Brand": "Brand A",
            "Category": "Clothing",
            "Subcategory": "T-Shirts",
            "Discount": 5.00,
            "Subtotal": 54.98
        },
        {
            "ProductID": "B003VSARVA",
            "ProductName": "Piper Cap",
            "ImageUrl": "https://m.media-amazon.com/images/I/31XwvOz-bmL._AC_UL320_.jpg",
            "Quantity": 1,
            "Price": 49.99,
            "Color": "Blue",
            "Size": "Large",
            "Brand": "Brand B",
            "Category": "Footwear",
            "Subcategory": "Sneakers",
            "Discount": 0.00,
            "Subtotal": 49.99
        }
        ],
        "TotalAmount": 104.97,
        "Status": "Pending",
        "ShippingAddress": {
        "Name": "Utsav Verma",
        "Street": "123 Main St",
        "City": "Cityville",
        "State": "ST",
        "ZipCode": "12345"
        },
        "BillingAddress": {
        "Name": "Utsav Verma",
        "Street": "456 Billing St",
        "City": "Cityville",
        "State": "ST",
        "ZipCode": "12345"
        },
        "PaymentMethod": "CreditCard",
        "PaymentStatus": "Paid",
        "ShippingMethod": "Standard",
        "DeliveryDate": "2024-01-10"
    },
    {
        "OrderID": "12345",
        "UserID": "user123",
        "OrderDate": "2024-01-01T12:00:00",
        "Products": [
            {
                "ProductID": "B0C4H2CHDV",
                "ProductName": "Boston Cap Unisex Baseball Cap Sun Hat Adjustable Trucker Cap",
                "ImageUrl": "https://m.media-amazon.com/images/I/516WGe4YvVL._AC_UL320_.jpg",
                "Quantity": 2,
                "Price": 29.99,
                "Color": "Red",
                "Size": "Medium",
                "Brand": "Brand A",
                "Category": "Clothing",
                "Subcategory": "T-Shirts",
                "Discount": 5.00,
                "Subtotal": 54.98
            },
            {
                "ProductID": "B003VSARVA",
                "ProductName": "Piper Cap",
                "ImageUrl": "https://m.media-amazon.com/images/I/31XwvOz-bmL._AC_UL320_.jpg",
                "Quantity": 1,
                "Price": 49.99,
                "Color": "Blue",
                "Size": "Large",
                "Brand": "Brand B",
                "Category": "Footwear",
                "Subcategory": "Sneakers",
                "Discount": 0.00,
                "Subtotal": 49.99
            }
        ],
        "TotalAmount": 104.97,
        "Status": "Pending",
        "ShippingAddress": {
        "Name": "Utsav Verma",
        "Street": "123 Main St",
        "City": "Cityville",
        "State": "ST",
        "ZipCode": "12345"
        },
        "BillingAddress": {
        "Name": "Utsav Verma",
        "Street": "456 Billing St",
        "City": "Cityville",
        "State": "ST",
        "ZipCode": "12345"
        },
        "PaymentMethod": "CreditCard",
        "PaymentStatus": "Paid",
        "ShippingMethod": "Standard",
        "DeliveryDate": "2024-01-10"
    }
]